# Generated by Django 3.0.8 on 2020-07-29 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Childrens', 'childrens'), ('Classics', 'classics'), ('Business', 'business'), ('Fantasy', 'fantasy'), ('History', 'history'), ('Horror', 'horror'), ('Mystery', 'mystery'), ('Nonfiction', 'nonfiction'), ('Romance', 'romance'), ('Sports', 'sports'), ('Science', 'science'), ('Young Adult', 'youngadult')], default='Classics', max_length=11)),
                ('author', models.CharField(max_length=100)),
                ('cover_image_link', models.CharField(max_length=100)),
                ('number_of_pages', models.IntegerField()),
                ('audible_link', models.CharField(default='N/A', max_length=100)),
                ('barnes_noble_link', models.CharField(default='N/A', max_length=100)),
                ('amazon_link', models.CharField(default='N/A', max_length=100)),
                ('google_link', models.CharField(default='N/A', max_length=100)),
                ('rating', models.IntegerField(default=1)),
                ('synopsis', models.TextField()),
            ],
        ),
    ]
