# Generated by Django 3.0.8 on 2020-07-30 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_it', '0002_auto_20200729_2039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='amazon_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='audible_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='barnes_noble_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='cover_image_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Childrens', 'childrens'), ('Classics', 'classics'), ('Business', 'business'), ('Fantasy', 'fantasy'), ('History', 'history'), ('Horror', 'horror'), ('Mystery', 'mystery'), ('Nonfiction', 'nonfiction'), ('Romance', 'romance'), ('Sports', 'sports'), ('Science', 'science'), ('Young Adult', 'youngadult')], max_length=11),
        ),
        migrations.AlterField(
            model_name='book',
            name='google_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='synopsis',
            field=models.TextField(),
        ),
    ]
