# Generated by Django 3.0.8 on 2020-07-30 04:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('read_it', '0004_auto_20200729_2147'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataForm',
            fields=[
                ('book_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='read_it.Book')),
            ],
            bases=('read_it.book',),
        ),
        migrations.AlterField(
            model_name='book',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=3, null=True),
        ),
    ]
