# Generated by Django 3.0.8 on 2020-07-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('read_it', '0005_auto_20200729_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('childrens', 'childrens'), ('classics', 'classics'), ('business', 'business'), ('fantasy', 'fantasy'), ('history', 'history'), ('horror', 'horror'), ('mystery', 'mystery'), ('nonfiction', 'nonfiction'), ('romance', 'romance'), ('sports', 'sports'), ('science', 'science'), ('young Adult', 'youngadult')], max_length=11),
        ),
    ]
