# Generated by Django 3.2.4 on 2021-07-17 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_it', '0008_auto_20200801_2216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataForm',
        ),
    ]
